Cleaning the file "01_fund_master.csv"

In [ ]:
import os

os.listdir("/content/")

['.config',
 '10_benchmark_indices.csv',
 '05_category_inflows.csv',
 '09_portfolio_holdings.csv',
 '03_aum_by_fund_house.csv',
 '07_scheme_performance.csv',
 '06_industry_folio_count.csv',
 '04_monthly_sip_inflows.csv',
 '01_fund_master.csv',
 '02_nav_history.csv',
 '08_investor_transactions.csv',
 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_csv('/content/01_fund_master.csv')
display(df.head())

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [ ]:
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [ ]:
df.shape

(40, 15)

In [ ]:
df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [ ]:
df.describe()

,amfi_code,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount
count,40.000000,40.000000,40.000000,40.0,40.000000
mean,120247.000000,1.237000,0.812500,500.0,1277.500000
std,14534.998667,0.386584,0.387091,0.0,1082.847031
min,100016.000000,0.550000,0.000000,500.0,100.000000
25%,118632.750000,0.787500,1.000000,500.0,1000.000000
50%,119551.500000,1.425000,1.000000,500.0,1000.000000
75%,120842.250000,1.540000,1.000000,500.0,1000.000000
max,149324.000000,1.640000,1.000000,500.0,5000.000000

In [ ]:
df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['launch_date'] = pd.to_datetime(df['launch_date'])

In [ ]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [ ]:
df['fund_house'].unique()
df['category'].unique()

array(['Equity', 'Debt'], dtype=object)

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_data_fund_master.csv'), index=False)

In [ ]:
import pandas as pd

df = pd.read_csv('/content/02_nav_history.csv')

Mutual-Fund-Analysis csv files reading

In [ ]:
df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [ ]:
df.shape

(46000, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [ ]:
df.describe()

           amfi_code           nav
count   46000.000000  46000.000000
mean   120247.000000    269.570265
std     14352.317221    577.187060
min    100016.000000     26.136600
25%    118632.750000     69.170425
50%    119551.500000    122.732150
75%    120842.250000    260.338675
max    149324.000000   4268.549700

In [ ]:
df.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["date"] = pd.to_datetime(df["date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[ns]
 2   nav        46000 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.1 MB

In [ ]:
df = df.sort_values(["amfi_code", "date"])

In [ ]:
df = df.drop_duplicates(subset=["amfi_code", "date"])

In [ ]:
df["nav"] = df.groupby("amfi_code")["nav"].ffill()

In [ ]:
print("NAV <= 0 :", (df["nav"] <= 0).sum())

NAV <= 0 : 0

In [ ]:
df = df[df["nav"] > 0]

In [ ]:
# Sort by AMFI Code and Date
df = df.sort_values(["amfi_code", "date"])

# Remove duplicate records
df = df.drop_duplicates(subset=["amfi_code", "date"])

# Forward fill missing NAV
df["nav"] = df.groupby("amfi_code")["nav"].ffill()

# Validate NAV values
print("Invalid NAV Values:", (df["nav"] <= 0).sum())

# Keep only valid NAV records
df = df[df["nav"] > 0]

Invalid NAV Values: 0

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_02_nav_history.csv'), index=False)

In [ ]:
import pandas as pd
df = pd.read_csv("03_aum_by_fund_house.csv")
df.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [ ]:
df.shape

(90, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

In [ ]:
df.describe()

       aum_lakh_crore     aum_crore  num_schemes
count       90.000000  9.000000e+01    90.000000
mean         4.352889  4.352889e+05   152.200000
std          2.734328  2.734328e+05    52.108832
min          1.050000  1.050000e+05    56.000000
25%          2.525000  2.525000e+05    95.000000
50%          3.450000  3.450000e+05   172.500000
75%          5.675000  5.675000e+05   195.000000
max         12.500000  1.250000e+06   216.000000

In [ ]:
df.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='object')

In [ ]:
df.columns = df.columns.str.lower().str.replace(" ","_")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

In [ ]:
df.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [ ]:
df['aum_crore'] = pd.to_numeric(df['aum_crore'], errors='coerce')

In [ ]:
df[df['aum_crore'] <= 0]

Empty DataFrame
Columns: [date, fund_house, aum_lakh_crore, aum_crore, num_schemes]
Index: []

In [ ]:
df = df[df['aum_crore'] > 0]

In [ ]:
df['fund_house'].unique()

array(['SBI Mutual Fund', 'ICICI Prudential MF', 'HDFC Mutual Fund',
       'Nippon India MF', 'Kotak Mahindra MF', 'Aditya Birla Sun Life MF',
       'Axis Mutual Fund', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [ ]:
df['fund_house'] = df['fund_house'].str.strip()

df['fund_house'] = df['fund_house'].str.title()

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, '03_aum_by_fund_house.csv'), index=False)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/04_monthly_sip_inflows.csv')
display(df.head())

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [ ]:
df.shape

(48, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

In [ ]:
df.columns

Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='object')

In [ ]:
df.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
df['yoy_growth_pct'] = df['yoy_growth_pct'].fillna(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['month'] = pd.to_datetime(df['month'])

In [ ]:
df.dtypes

month                        datetime64[ns]
sip_inflow_crore                      int64
active_sip_accounts_crore           float64
new_sip_accounts_lakh               float64
sip_aum_lakh_crore                  float64
yoy_growth_pct                      float64
dtype: object

In [ ]:
df[['sip_inflow_crore',
    'active_sip_accounts_crore',
    'new_sip_accounts_lakh',
    'sip_aum_lakh_crore',
    'yoy_growth_pct']] = df[[
    'sip_inflow_crore',
    'active_sip_accounts_crore',
    'new_sip_accounts_lakh',
    'sip_aum_lakh_crore',
    'yoy_growth_pct'
]].apply(pd.to_numeric, errors='coerce')

In [ ]:
df[df['sip_inflow_crore'] < 0]

Empty DataFrame
Columns: [month, sip_inflow_crore, active_sip_accounts_crore, new_sip_accounts_lakh, sip_aum_lakh_crore, yoy_growth_pct]
Index: []

In [ ]:
df[df['active_sip_accounts_crore'] < 0]

Empty DataFrame
Columns: [month, sip_inflow_crore, active_sip_accounts_crore, new_sip_accounts_lakh, sip_aum_lakh_crore, yoy_growth_pct]
Index: []

In [ ]:
df[df['new_sip_accounts_lakh'] < 0]

Empty DataFrame
Columns: [month, sip_inflow_crore, active_sip_accounts_crore, new_sip_accounts_lakh, sip_aum_lakh_crore, yoy_growth_pct]
Index: []

In [ ]:
df[df['sip_aum_lakh_crore'] < 0]

Empty DataFrame
Columns: [month, sip_inflow_crore, active_sip_accounts_crore, new_sip_accounts_lakh, sip_aum_lakh_crore, yoy_growth_pct]
Index: []

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, '04_monthly_sip_inflows.csv'), index=False)

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import os

In [ ]:
path = "/content/"

In [ ]:
files = [
    '10_benchmark_indices.csv',
    '09_portfolio_holdings.csv',
    '07_scheme_performance.csv',
    '06_industry_folio_count.csv',
    '05_category_inflows.csv',
    '08_investor_transactions.csv'
]

In [ ]:
data = {}

for file in files:

    df = pd.read_csv(path + file)

    data[file] = df

    print("==========================")
    print("FILE NAME:", file)
    print("==========================")
    print("Shape:", df.shape)
    print()
    print(df.head())
    print()

==========================
FILE NAME: 10_benchmark_indices.csv
==========================
Shape: (8050, 3)

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

==========================
FILE NAME: 09_portfolio_holdings.csv
==========================
Shape: (322, 8)

   amfi_code stock_symbol                stock_name       sector  weight_pct  \
0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85
1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19
2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90
3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76
4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25

   market_value_cr  current_price_inr portfolio_date
0           737.09            6011.08     2025-12-31
1            88.97            1074.65     2025-12-31
2           208.45            5964.59     2025-12-31
3           161.32            3748.82     2025-12-31
4           725.90            1321.45     2025-12-31

==========================
FILE NAME: 07_scheme_performance.csv
==========================
Shape: (40, 19)

   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

==========================
FILE NAME: 06_industry_folio_count.csv
==========================
Shape: (21, 6)

     month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0  2022-01               13.26                 9.28               1.86
1  2022-04               13.91                 9.74               1.95
2  2022-07               13.85                 9.69               1.94
3  2022-10               14.12                 9.88               1.98
4  2023-01               14.81                10.37               2.07

   hybrid_folios_crore  others_folios_crore
0                 0.80                 1.33
1                 0.83                 1.39
2                 0.83                 1.38
3                 0.85                 1.41
4                 0.89                 1.48

==========================
FILE NAME: 05_category_inflows.csv
==========================
Shape: (144, 3)

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

==========================
FILE NAME: 08_investor_transactions.csv
==========================
Shape: (32778, 13)

  investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0   INV003054       2024-01-01     119092              SIP        1834
1   INV002952       2024-01-01     148567       Redemption      392882
2   INV003420       2024-01-01     118636              SIP         912
3   INV003436       2024-01-01     118634              SIP        1102
4   INV004691       2024-01-01     119094          Lumpsum        8682

         state       city city_tier age_group  gender  annual_income_lakh  \
0    Telangana  Hyderabad       T30       56+  Female                77.1
1       Punjab   Amritsar       B30     18-25    Male                 7.1
2      Haryana  Faridabad       B30     36-45    Male                47.2
3  Maharashtra     Mumbai       T30     36-45  Female                54.4
4        Delhi      Noida       T30     26-35    Male                14.5

  payment_mode kyc_status
0          UPI   Verified
1       Cheque   Verified
2      Mandate   Verified
3       Cheque    Pending
4  Net Banking    Pending

In [ ]:
data.keys()

dict_keys(['10_benchmark_indices.csv', '09_portfolio_holdings.csv', '07_scheme_performance.csv', '06_industry_folio_count.csv', '05_category_inflows.csv', '08_investor_transactions.csv'])

In [ ]:
for name,df in data.items():

    print("\nFILE:",name)
    print(df.columns.tolist())

FILE: 10_benchmark_indices.csv
['date', 'index_name', 'close_value']

FILE: 09_portfolio_holdings.csv
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

FILE: 07_scheme_performance.csv
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']

FILE: 06_industry_folio_count.csv
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

FILE: 05_category_inflows.csv
['month', 'category', 'net_inflow_crore']

FILE: 08_investor_transactions.csv
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

In [ ]:
benchmark = data['10_benchmark_indices.csv'].copy()

benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [ ]:
benchmark.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

In [ ]:
benchmark.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [ ]:
benchmark.duplicated().sum()

np.int64(0)

In [ ]:
benchmark.drop_duplicates(inplace=True)

In [ ]:
benchmark['date'] = pd.to_datetime(
    benchmark['date'],
    errors='coerce'
)

In [ ]:
benchmark.dtypes

date           datetime64[ns]
index_name             object
close_value           float64
dtype: object

In [ ]:
benchmark['close_value'] = pd.to_numeric(
    benchmark['close_value'],
    errors='coerce'
)

In [ ]:
benchmark = benchmark[
    benchmark['close_value'] > 0
]

In [ ]:
benchmark = benchmark.sort_values(
    by=['index_name','date']
)

In [ ]:
benchmark.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [ ]:
benchmark.shape

(8050, 3)

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_10_benchmark_indices.csv'), index=False)

In [ ]:
import pandas as pd

df = pd.read_csv("/content/10_benchmark_indices.csv")

df.columns

Index(['date', 'index_name', 'close_value'], dtype='object')

In [ ]:
import os

os.listdir("/content/")

['.config',
 '10_benchmark_indices.csv',
 '05_category_inflows.csv',
 '09_portfolio_holdings.csv',
 '03_aum_by_fund_house.csv',
 '07_scheme_performance.csv',
 '06_industry_folio_count.csv',
 '04_monthly_sip_inflows.csv',
 '01_fund_master.csv',
 '02_nav_history.csv',
 '08_investor_transactions.csv',
 'sample_data']

In [ ]:
df = pd.read_csv('/content/05_category_inflows.csv')
df.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [ ]:
df.tail()

       month           category  net_inflow_crore
139  2025-03  Sectoral/Thematic            8614.0
140  2025-03             Liquid           38681.0
141  2025-03     Short Duration            4886.0
142  2025-03               Gilt             956.0
143  2025-03             Hybrid            2830.0

In [ ]:
df.columns

Index(['month', 'category', 'net_inflow_crore'], dtype='object')

In [ ]:
df.shape

(144, 3)

In [ ]:
df.dtypes

month                object
category             object
net_inflow_crore    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

In [ ]:
df.describe()

       net_inflow_crore
count        144.000000
mean        6473.881944
std         9718.335947
min          437.000000
25%         1801.250000
50%         4148.000000
75%         5304.000000
max        41952.000000

In [ ]:
df.describe(include='object')

          month   category
count       144        144
unique       12         12
top     2024-04  Large Cap
freq         12         12

In [ ]:
df.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.columns

Index(['month', 'category', 'net_inflow_crore'], dtype='object')

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
obj = df.select_dtypes(include='object').columns
for col in obj:
    df[col] = df[col].str.strip()

In [ ]:
for col in obj:
    print(col)
    print(df[col].unique())

month
['2024-04' '2024-05' '2024-06' '2024-07' '2024-08' '2024-09' '2024-10'
 '2024-11' '2024-12' '2025-01' '2025-02' '2025-03']
category
['Large Cap' 'Mid Cap' 'Small Cap' 'Flexi Cap' 'Large & Mid Cap' 'ELSS'
 'Value/Contra' 'Sectoral/Thematic' 'Liquid' 'Short Duration' 'Gilt'
 'Hybrid']

In [ ]:
df['month'] = pd.to_datetime(df['month'], format='%Y-%m')

In [ ]:
df.select_dtypes(include=np.number).columns

Index(['net_inflow_crore'], dtype='object')

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_05_category_inflows.csv'), index=False)

In [ ]:
df = pd.read_csv('/content/06_industry_folio_count.csv')
df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [ ]:
df.columns

Index(['month', 'total_folios_crore', 'equity_folios_crore',
       'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore'],
      dtype='object')

In [ ]:
df.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [ ]:
df.tail()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
16,2025-07,24.57,17.20,3.44,1.47,2.46
17,2025-08,24.89,17.42,3.48,1.49,2.49
18,2025-09,25.19,17.63,3.53,1.51,2.52
19,2025-10,25.60,17.92,3.58,1.54,2.56
20,2025-12,26.12,18.28,3.66,1.57,2.61

In [ ]:
df.shape

(21, 6)

In [ ]:
df.dtypes

month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

In [ ]:
df.describe()

,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
count,21.000000,21.000000,21.000000,21.000000,21.000000
mean,19.829524,13.880476,2.776190,1.190000,1.983333
std,4.583376,3.207799,0.640308,0.274864,0.459079
min,13.260000,9.280000,1.860000,0.800000,1.330000
25%,15.540000,10.880000,2.180000,0.930000,1.550000
50%,19.980000,13.990000,2.800000,1.200000,2.000000
75%,23.890000,16.720000,3.340000,1.430000,2.390000
max,26.120000,18.280000,3.660000,1.570000,2.610000

In [ ]:
df.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns = df.columns.str.strip()

df['month'] = df['month'].astype(str).str.strip()

In [ ]:
df['month'] = pd.to_datetime(df['month'])

In [ ]:
df['month'] = pd.to_datetime(df['month'], errors='coerce')

In [ ]:
df[df['month'].isnull()]

Empty DataFrame
Columns: [month, total_folios_crore, equity_folios_crore, debt_folios_crore, hybrid_folios_crore, others_folios_crore]
Index: []

In [ ]:
cols = [
    'total_folios_crore',
    'equity_folios_crore',
    'debt_folios_crore',
    'hybrid_folios_crore',
    'others_folios_crore'
]

df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
df.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [ ]:
df = df.sort_values('month')

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_06_industry_folio_count.csv'), index=False)

In [ ]:
import pandas as pd
df = pd.read_csv('/content/07_scheme_performance.csv')
df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

### Cleaning `07_scheme_performance.csv`

In [ ]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [ ]:
df['amfi_code'] = df['amfi_code'].astype(str)

In [ ]:
text_cols = [
    'scheme_name',
    'fund_house',
    'category',
    'plan',
    'risk_grade'
]

for col in text_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.title()
    )

In [ ]:
numeric_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct',
    'alpha',
    'beta',
    'sharpe_ratio',
    'sortino_ratio',
    'std_dev_ann_pct',
    'max_drawdown_pct',
    'aum_crore',
    'expense_ratio_pct',
    'morningstar_rating'
]

df[numeric_cols] = df[numeric_cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [ ]:
return_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct'
]


for col in return_cols:
    print(
        col,
        "Non Numeric Values:",
        df[col].isnull().sum()
    )

return_1yr_pct Non Numeric Values: 0
return_3yr_pct Non Numeric Values: 0
return_5yr_pct Non Numeric Values: 0
benchmark_3yr_pct Non Numeric Values: 0

In [ ]:
df['anomaly_flag'] = False

In [ ]:
df.loc[
    (df['return_1yr_pct'] > 100) |
    (df['return_1yr_pct'] < -100),
    'anomaly_flag'
] = True

In [ ]:
df.loc[
    (df['expense_ratio_pct'] < 0.1) |
    (df['expense_ratio_pct'] > 2.5),
    'anomaly_flag'
] = True

In [ ]:
df.loc[
    (df['sharpe_ratio'] > 10) |
    (df['sharpe_ratio'] < -10),
    'anomaly_flag'
] = True

In [ ]:
print(
    "Total Anomalies:",
    df['anomaly_flag'].sum()
)

Total Anomalies: 0

In [ ]:
print(
    "Invalid Expense Ratio:",
    (
        (df['expense_ratio_pct'] < 0.1) |
        (df['expense_ratio_pct'] > 2.5)
    ).sum()
)

Invalid Expense Ratio: 0

In [ ]:
print('Missing values before fillna:')
print(df[numeric_cols].isnull().sum())

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

print('\nMissing values after fillna:')
print(df[numeric_cols].isnull().sum())

Missing values before fillna:
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
dtype: int64

Missing values after fillna:
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
dtype: int64

In [ ]:
df[text_cols] = df[text_cols].fillna("Unknown")

In [ ]:
print("AUM less than 0:", (df['aum_crore'] < 0).sum())
df = df[df['aum_crore'] >= 0]

AUM less than 0: 0

In [ ]:
print("Expense ratio less than 0:", (df['expense_ratio_pct'] < 0).sum())
df = df[df['expense_ratio_pct'] >= 0]

Expense ratio less than 0: 0

In [ ]:
print("Invalid Morningstar ratings:", df[~df['morningstar_rating'].isin([1,2,3,4,5])].shape[0])
df = df[
    (df['morningstar_rating'] >= 1) &
    (df['morningstar_rating'] <= 5)
]

Invalid Morningstar ratings: 0

In [ ]:
print("Beta less than 0:", (df['beta'] < 0).sum())
df = df[df['beta'] >= 0]

Beta less than 0: 0

In [ ]:
df = df.sort_values(
    ['fund_house','category']
).reset_index(
    drop=True,
    inplace=False
)

In [ ]:
print("Final Dataset Shape:", df.shape)

print("\nExpense Ratio Range:")
print(df['expense_ratio_pct'].min())
print(df['expense_ratio_pct'].max())


print("\nAnomaly Count:")
print(df['anomaly_flag'].value_counts())

Final Dataset Shape: (40, 20)

Expense Ratio Range:
0.55
1.64

Anomaly Count:
anomaly_flag
False    40
Name: count, dtype: int64

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_07_scheme_performance.csv'), index=False)

In [ ]:
df.tail()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,Large & Mid Cap,Regular,14.91,14.56,15.68,12.86,1.70,0.99,0.91,1.55,16.0,-33.15,49046,1.52,5,Moderately High
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,Mirae Asset MF,ELSS,Regular,11.16,13.58,14.26,13.04,0.54,0.98,0.80,1.03,17.0,-22.62,2989,1.60,5,High
37,149322,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,Large Cap,Regular,11.96,12.82,12.35,11.00,1.82,0.91,0.92,1.63,14.0,-21.70,41828,1.54,5,Moderate
38,149323,DSP Midcap Fund - Regular - Growth,DSP Mutual Fund,Mid Cap,Regular,14.12,17.16,19.00,16.14,1.02,0.98,0.90,1.50,19.0,-26.99,37835,1.61,4,High
39,149324,DSP Small Cap Fund - Regular - Growth,DSP Mutual Fund,Small Cap,Regular,20.20,20.08,20.61,19.39,0.69,0.98,0.80,1.23,25.0,-17.01,35124,1.52,4,Very High

In [ ]:
df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

In [ ]:
df.shape

(40, 19)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [ ]:
df.describe()

,amfi_code,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.00000,40.000000,40.000000
mean,120247.000000,14.376000,14.089000,14.516750,12.835500,1.253500,0.873250,1.361750,2.082500,14.962500,-19.200250,26091.60000,1.237000,4.250000
std,14534.998667,4.883023,4.617253,4.454021,4.740972,0.447412,0.224846,1.475805,2.203144,6.669282,8.819164,13809.11134,0.386584,0.742484
min,100016.000000,4.260000,5.140000,5.430000,3.960000,0.510000,0.220000,0.800000,1.030000,0.500000,-33.500000,979.00000,0.550000,3.000000
25%,118632.750000,11.735000,12.035000,12.340000,10.690000,0.887500,0.890000,0.865000,1.270000,14.000000,-25.062500,17400.50000,0.787500,4.000000
50%,119551.500000,14.620000,14.205000,14.185000,13.090000,1.205000,0.960000,0.925000,1.445000,14.000000,-20.600000,26713.00000,1.425000,4.000000
75%,120842.250000,16.392500,15.882500,17.585000,14.775000,1.700000,1.000000,0.985000,1.637500,19.000000,-14.255000,38125.00000,1.540000,5.000000
max,149324.000000,24.930000,23.390000,23.800000,22.160000,1.980000,1.040000,7.680000,10.370000,25.000000,-2.230000,49046.00000,1.640000,5.000000

In [ ]:
df.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [ ]:
df.isnull().describe()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
count,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
unique,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
freq,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40

In [ ]:
df['amfi_code'].dtype

dtype('int64')

In [ ]:
df['amfi_code'] = df['amfi_code'].astype(str)

In [ ]:
text_cols = [
    'scheme_name',
    'fund_house',
    'category',
    'plan',
    'risk_grade'
]


for col in text_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.title()
    )

In [ ]:
numeric_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct',
    'alpha',
    'beta',
    'sharpe_ratio',
    'sortino_ratio',
    'std_dev_ann_pct',
    'max_drawdown_pct',
    'aum_crore',
    'expense_ratio_pct',
    'morningstar_rating'
]


df[numeric_cols] = df[numeric_cols].apply(
    pd.to_numeric,
    errors='coerce'
)

In [ ]:
df[numeric_cols].isnull().sum()

return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
dtype: int64

In [ ]:
df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

In [ ]:
df[text_cols] = df[text_cols].fillna("Unknown")

In [ ]:
(df['aum_crore'] < 0).sum()

np.int64(0)

In [ ]:
df = df[df['aum_crore'] >= 0]

In [ ]:
df[df['expense_ratio_pct'] < 0]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [ ]:
df = df[df['expense_ratio_pct'] >= 0]

In [ ]:
df['morningstar_rating'].unique()

array([4, 3, 5])

In [ ]:
df = df[
    (df['morningstar_rating'] >= 1) &
    (df['morningstar_rating'] <= 5)
]

In [ ]:
df[df['beta'] < 0]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [ ]:
df = df.sort_values(
    ['fund_house','category']
)

In [ ]:
df.reset_index(
    drop=True,
    inplace=True
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     object
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(2), object(6)
memory usage: 6.1+ KB

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_07_scheme_performance.csv'), index=False)

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv('/content/08_investor_transactions.csv')
df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [ ]:
df.tail()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [ ]:
df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='object')

In [ ]:
df.shape

(32778, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [ ]:
df.describe()

           amfi_code     amount_inr  annual_income_lakh
count   32778.000000   32778.000000        32778.000000
mean   120264.617518  107437.318628           26.181219
std     14370.205345  150415.905084           20.805425
min    100016.000000     400.000000            3.000000
25%    118632.000000    3153.000000           10.600000
50%    119551.000000   17782.500000           19.700000
75%    120843.000000  189324.250000           37.400000
max    149324.000000  597498.000000           99.700000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

df.shape

(32778, 13)

In [ ]:
df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [ ]:
num_cols = df.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [ ]:
df['transaction_type'].unique()

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

In [ ]:
df['transaction_type'] = (
    df['transaction_type']
    .str.strip()
    .str.lower()
)

df['transaction_type'] = df['transaction_type'].replace({
    'sip':'SIP',
    'lumpsum':'Lumpsum',
    'lump sum':'Lumpsum',
    'lump-sum':'Lumpsum',
    'redemption':'Redemption'
})

In [ ]:
print(df['transaction_type'].value_counts())

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [ ]:
print("Invalid Amount:",
      (df['amount_inr'] <= 0).sum())

Invalid Amount: 0

In [ ]:
df = df[df['amount_inr'] > 0]

In [ ]:
df['transaction_date'] = pd.to_datetime(
    df['transaction_date'],
    errors='coerce'
)

In [ ]:
print("Invalid Dates:",
      df['transaction_date'].isnull().sum())

Invalid Dates: 0

In [ ]:
df = df.dropna(subset=['transaction_date'])

In [ ]:
df['kyc_status'].unique()

array(['Verified', 'Pending'], dtype=object)

In [ ]:
valid_kyc = [
    'Verified',
    'Pending',
    'Rejected'
]


invalid_kyc = df[
    ~df['kyc_status'].isin(valid_kyc)
]


print("Invalid KYC Records:",
      invalid_kyc.shape[0])

Invalid KYC Records: 0

In [ ]:
df = df[df['kyc_status'].isin(valid_kyc)]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [ ]:
df['transaction_type'].value_counts()

transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

In [ ]:
df['payment_mode'].value_counts()

payment_mode
Net Banking    8250
Cheque         8228
UPI            8154
Mandate        8146
Name: count, dtype: int64

In [ ]:
df['city_tier'].value_counts()

city_tier
T30    21719
B30    11059
Name: count, dtype: int64

In [ ]:
df['kyc_status'].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [ ]:
print("Final Shape:",df.shape)

print("\nTransaction Types:")
print(df['transaction_type'].value_counts())

print("\nKYC Status:")
print(df['kyc_status'].value_counts())

print("\nInvalid Amount:")
print((df['amount_inr'] <= 0).sum())

Final Shape: (32778, 13)

Transaction Types:
transaction_type
SIP           19716
Lumpsum        8095
Redemption     4967
Name: count, dtype: int64

KYC Status:
kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

Invalid Amount:
0

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_08_investor_transactions.csv'), index=False)

In [ ]:
df = pd.read_csv('/09_portfolio_holdings.csv')
df.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [ ]:
df.tail()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
317,149324,DIVISLAB,Divi's Laboratories,Pharma,9.54,855.88,7453.05,2025-12-31
318,149324,BHARTIARTL,Bharti Airtel Ltd,Telecom,1.79,969.71,924.41,2025-12-31
319,149324,TCS,Tata Consultancy Services,IT,13.17,1637.69,1927.89,2025-12-31
320,149324,INDUSINDBK,IndusInd Bank Ltd,Banking,7.63,1387.30,3208.86,2025-12-31
321,149324,NTPC,NTPC Ltd,Utilities,2.04,1303.55,5797.95,2025-12-31

In [ ]:
df.columns

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='object')

In [ ]:
df.shape

(322, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 20.3+ KB

In [ ]:
df.describe()

           amfi_code  weight_pct  market_value_cr  current_price_inr
count     322.000000  322.000000       322.000000         322.000000
mean   121210.434783   10.558975      1008.846646        4080.870528
std     14669.377920    6.060137       543.827535        2265.186353
min    100016.000000    0.990000        55.740000         246.780000
25%    118633.000000    6.015000       513.702500        2081.985000
50%    119552.000000    9.395000      1045.670000        4138.995000
75%    120842.750000   13.917500      1477.502500        5914.307500
max    149324.000000   38.180000      1999.500000        7942.960000

In [ ]:
df.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

In [ ]:
df['portfolio_date'] = pd.to_datetime(df['portfolio_date'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 20.3+ KB

In [ ]:
df['sector'].value_counts()

sector
Banking           60
IT                40
Pharma            38
Automobile        33
Utilities         24
Infrastructure    22
FMCG              21
Telecom           15
Diversified       14
Energy            13
Cement            12
NBFC              11
Paints            10
Consumer Goods     9
Name: count, dtype: int64

In [ ]:
df['stock_symbol'].nunique()

30

In [ ]:
df['amfi_code'].nunique()

34

In [ ]:
import os

output_dir = '../Cleaned_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

df.to_csv(os.path.join(output_dir, 'Cleaned_09_portfolio_holidings.csv'), index=False)